# Generated by Django 4.0.2 on 2022-03-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
